-- LEGACY SAFETY NOTICE
--
-- This file is legacy reference material, not an actual-database baseline.
-- DO NOT EXECUTE this file against any database.
-- The only source of truth for database changes is supabase/migrations/.
-- The former contents are quarantined under supabase/legacy/ for audit purposes.
-- They included policies that exposed PII to anonymous users and must never be reused.
